<?php

namespace Database\Seeders;

use App\Models\AssessmentCriterion;
use Illuminate\Database\Seeder;

class AssessmentCriteriaSeeder extends Seeder
{
    public function run(): void
    {
        $criteria = [
            ['code' => 'D01', 'category' => 'DRIVER', 'sub_category' => 'Administrasi', 'name' => 'SIM sesuai jenis kendaraan dan masih berlaku', 'weight' => 4.0, 'is_mandatory' => true, 'evidence_minimum' => 'Salinan/foto SIM', 'pic_verification' => 'HSE / Fleet', 'frequency' => 'Tahunan & monitoring', 'notes' => 'Kritis'],
            ['code' => 'D02', 'category' => 'DRIVER', 'sub_category' => 'Administrasi', 'name' => 'Identitas driver sesuai database/penugasan', 'weight' => 2.0, 'is_mandatory' => true, 'evidence_minimum' => 'Database/ID', 'pic_verification' => 'HSE / Ops', 'frequency' => 'Setiap assessment', 'notes' => null],
            ['code' => 'D03', 'category' => 'DRIVER', 'sub_category' => 'Administrasi', 'name' => 'Surat/izin mengemudi internal sesuai ketentuan perusahaan', 'weight' => 2.0, 'is_mandatory' => true, 'evidence_minimum' => 'Izin/ID internal', 'pic_verification' => 'HSE / Ops', 'frequency' => 'Tahunan', 'notes' => null],
            ['code' => 'D04', 'category' => 'DRIVER', 'sub_category' => 'Administrasi', 'name' => 'MCU/fit to work masih berlaku sesuai kebijakan', 'weight' => 3.0, 'is_mandatory' => true, 'evidence_minimum' => 'Bukti MCU', 'pic_verification' => 'HSE / HR', 'frequency' => 'Sesuai kebijakan', 'notes' => null],
            ['code' => 'D05', 'category' => 'DRIVER', 'sub_category' => 'Administrasi', 'name' => 'Bukti pemeriksaan/pengendalian Napza sesuai program perusahaan', 'weight' => 4.0, 'is_mandatory' => true, 'evidence_minimum' => 'Bukti pemeriksaan', 'pic_verification' => 'HSE / HR', 'frequency' => 'Sesuai program', 'notes' => 'Kritis'],
            ['code' => 'D06', 'category' => 'DRIVER', 'sub_category' => 'Kompetensi', 'name' => 'Pelatihan/sertifikasi defensive driving tersedia', 'weight' => 2.0, 'is_mandatory' => false, 'evidence_minimum' => 'Sertifikat/daftar hadir', 'pic_verification' => 'HSE', 'frequency' => 'Tahunan', 'notes' => null],
            ['code' => 'D07', 'category' => 'DRIVER', 'sub_category' => 'Kompetensi', 'name' => 'Safety induction/briefing perjalanan dipahami dan terdokumentasi', 'weight' => 2.0, 'is_mandatory' => false, 'evidence_minimum' => 'Form/attendance', 'pic_verification' => 'HSE / Ops', 'frequency' => 'Periodik', 'notes' => null],
            ['code' => 'D08', 'category' => 'DRIVER', 'sub_category' => 'Kinerja', 'name' => 'Riwayat kecelakaan/insiden dan tindak lanjut terdokumentasi', 'weight' => 2.0, 'is_mandatory' => false, 'evidence_minimum' => 'Incident record', 'pic_verification' => 'HSE', 'frequency' => 'Bulanan', 'notes' => null],
            ['code' => 'D09', 'category' => 'DRIVER', 'sub_category' => 'Kinerja', 'name' => 'Riwayat pelanggaran/komplain dan tindak lanjut terdokumentasi', 'weight' => 2.0, 'is_mandatory' => false, 'evidence_minimum' => 'Record/BA', 'pic_verification' => 'HSE / Ops', 'frequency' => 'Bulanan', 'notes' => null],
            ['code' => 'D10', 'category' => 'DRIVER', 'sub_category' => 'Behavior Safety', 'name' => 'Seat belt digunakan setiap perjalanan', 'weight' => 3.0, 'is_mandatory' => true, 'evidence_minimum' => 'Observasi/telematics', 'pic_verification' => 'HSE', 'frequency' => 'Spot check', 'notes' => null],
            ['code' => 'D11', 'category' => 'DRIVER', 'sub_category' => 'Behavior Safety', 'name' => 'Tidak menggunakan HP saat kendaraan bergerak', 'weight' => 3.0, 'is_mandatory' => true, 'evidence_minimum' => 'Observasi/telematics', 'pic_verification' => 'HSE', 'frequency' => 'Spot check', 'notes' => null],
            ['code' => 'D12', 'category' => 'DRIVER', 'sub_category' => 'Behavior Safety', 'name' => 'Mematuhi batas kecepatan yang ditetapkan', 'weight' => 3.0, 'is_mandatory' => true, 'evidence_minimum' => 'Telematics/observasi', 'pic_verification' => 'HSE / Fleet', 'frequency' => 'Bulanan', 'notes' => null],
            ['code' => 'D13', 'category' => 'DRIVER', 'sub_category' => 'Behavior Safety', 'name' => 'Mematuhi rambu, marka dan aturan lalu lintas', 'weight' => 2.0, 'is_mandatory' => true, 'evidence_minimum' => 'Observasi/record', 'pic_verification' => 'HSE', 'frequency' => 'Spot check', 'notes' => null],
            ['code' => 'D14', 'category' => 'DRIVER', 'sub_category' => 'Fitness for Duty', 'name' => 'Tidak mengemudi dalam kondisi mengantuk/fatigue berisiko', 'weight' => 2.0, 'is_mandatory' => true, 'evidence_minimum' => 'Checklist fitness', 'pic_verification' => 'HSE / Ops', 'frequency' => 'Setiap perjalanan', 'notes' => null],
            ['code' => 'D15', 'category' => 'DRIVER', 'sub_category' => 'Pre-Trip', 'name' => 'Melakukan pemeriksaan kendaraan sebelum operasional', 'weight' => 2.0, 'is_mandatory' => true, 'evidence_minimum' => 'Pre-trip checklist', 'pic_verification' => 'Driver / HSE', 'frequency' => 'Harian', 'notes' => null],
            
            ['code' => 'D16', 'category' => 'KENDARAAN', 'sub_category' => 'Administrasi', 'name' => 'STNK/registrasi kendaraan masih berlaku', 'weight' => 3.0, 'is_mandatory' => true, 'evidence_minimum' => 'Dokumen kendaraan', 'pic_verification' => 'Fleet', 'frequency' => 'Tahunan', 'notes' => null],
            ['code' => 'D17', 'category' => 'KENDARAAN', 'sub_category' => 'Administrasi', 'name' => 'KIR/uji berkala sesuai jenis kendaraan dan ketentuan', 'weight' => 3.0, 'is_mandatory' => true, 'evidence_minimum' => 'Bukti uji berkala', 'pic_verification' => 'Fleet / HSE', 'frequency' => 'Sesuai masa berlaku', 'notes' => null],
            ['code' => 'D18', 'category' => 'KENDARAAN', 'sub_category' => 'Administrasi', 'name' => 'Dokumen/Identitas kendaraan lengkap dan sesuai database', 'weight' => 2.0, 'is_mandatory' => true, 'evidence_minimum' => 'Database kendaraan', 'pic_verification' => 'Fleet', 'frequency' => 'Tahunan', 'notes' => null],
            ['code' => 'D19', 'category' => 'KENDARAAN', 'sub_category' => 'Administrasi', 'name' => 'Asuransi/perlindungan kendaraan sesuai kebijakan', 'weight' => 1.0, 'is_mandatory' => false, 'evidence_minimum' => 'Polis/bukti', 'pic_verification' => 'Fleet', 'frequency' => 'Tahunan', 'notes' => null],
            ['code' => 'D20', 'category' => 'KENDARAAN', 'sub_category' => 'Safety', 'name' => 'Seat belt seluruh posisi yang dipersyaratkan berfungsi', 'weight' => 3.0, 'is_mandatory' => true, 'evidence_minimum' => 'Foto/inspeksi', 'pic_verification' => 'HSE / Fleet', 'frequency' => 'Bulanan', 'notes' => null],
            ['code' => 'D21', 'category' => 'KENDARAAN', 'sub_category' => 'Safety', 'name' => 'Ban, tekanan dan tread dalam kondisi layak', 'weight' => 3.0, 'is_mandatory' => true, 'evidence_minimum' => 'Foto/ukur', 'pic_verification' => 'HSE / Fleet', 'frequency' => 'Harian/Bulanan', 'notes' => null],
            ['code' => 'D22', 'category' => 'KENDARAAN', 'sub_category' => 'Safety', 'name' => 'Sistem pengereman berfungsi baik dan tidak ada indikasi abnormal', 'weight' => 4.0, 'is_mandatory' => true, 'evidence_minimum' => 'Inspeksi/maintenance', 'pic_verification' => 'Fleet', 'frequency' => 'Harian/periodik', 'notes' => 'Kritis'],
            ['code' => 'D23', 'category' => 'KENDARAAN', 'sub_category' => 'Safety', 'name' => 'Lampu utama, rem, sein dan hazard berfungsi', 'weight' => 2.0, 'is_mandatory' => true, 'evidence_minimum' => 'Functional test', 'pic_verification' => 'Driver / Fleet', 'frequency' => 'Harian', 'notes' => null],
            ['code' => 'D24', 'category' => 'KENDARAAN', 'sub_category' => 'Safety', 'name' => 'Spion, kaca dan wiper memberikan visibilitas memadai', 'weight' => 2.0, 'is_mandatory' => true, 'evidence_minimum' => 'Foto/inspeksi', 'pic_verification' => 'Driver / Fleet', 'frequency' => 'Harian', 'notes' => null],
            ['code' => 'D25', 'category' => 'KENDARAAN', 'sub_category' => 'Emergency Equipment', 'name' => 'APAR tersedia, sesuai kebutuhan dan status inspeksi baik', 'weight' => 3.0, 'is_mandatory' => true, 'evidence_minimum' => 'Foto/tag inspeksi', 'pic_verification' => 'HSE', 'frequency' => 'Bulanan', 'notes' => null],
            ['code' => 'D26', 'category' => 'KENDARAAN', 'sub_category' => 'Emergency Equipment', 'name' => 'P3K tersedia dan isi sesuai checklist', 'weight' => 3.0, 'is_mandatory' => true, 'evidence_minimum' => 'Foto/checklist', 'pic_verification' => 'HSE', 'frequency' => 'Bulanan', 'notes' => null],
            ['code' => 'D27', 'category' => 'KENDARAAN', 'sub_category' => 'Emergency Equipment', 'name' => 'Segitiga pengaman/emergency equipment tersedia', 'weight' => 1.0, 'is_mandatory' => true, 'evidence_minimum' => 'Foto', 'pic_verification' => 'Driver / Fleet', 'frequency' => 'Bulanan', 'notes' => null],
            ['code' => 'D28', 'category' => 'KENDARAAN', 'sub_category' => 'Safety', 'name' => 'Kelistrikan, battery dan kabel dalam kondisi aman', 'weight' => 2.0, 'is_mandatory' => true, 'evidence_minimum' => 'Foto/checklist', 'pic_verification' => 'Fleet', 'frequency' => 'Bulanan', 'notes' => null],
            ['code' => 'D29', 'category' => 'KENDARAAN', 'sub_category' => 'Safety', 'name' => 'Steering/suspension tidak menunjukkan kondisi abnormal', 'weight' => 3.0, 'is_mandatory' => true, 'evidence_minimum' => 'Inspeksi/maintenance', 'pic_verification' => 'Fleet', 'frequency' => 'Bulanan', 'notes' => null],
            ['code' => 'D30', 'category' => 'KENDARAAN', 'sub_category' => 'Safety', 'name' => 'Kebersihan kabin dan area operasional mendukung keselamatan', 'weight' => 1.0, 'is_mandatory' => false, 'evidence_minimum' => 'Foto', 'pic_verification' => 'Driver / Ops', 'frequency' => 'Harian', 'notes' => null],
            
            ['code' => 'D31', 'category' => 'MAINTENANCE', 'sub_category' => 'Preventive', 'name' => 'Jadwal preventive maintenance tersedia dan terkendali', 'weight' => 3.0, 'is_mandatory' => true, 'evidence_minimum' => 'Schedule/record', 'pic_verification' => 'Fleet', 'frequency' => 'Bulanan', 'notes' => null],
            ['code' => 'D32', 'category' => 'MAINTENANCE', 'sub_category' => 'Preventive', 'name' => 'Service dilakukan sesuai interval yang ditetapkan', 'weight' => 3.0, 'is_mandatory' => true, 'evidence_minimum' => 'Work order/invoice', 'pic_verification' => 'Fleet', 'frequency' => 'Periodik', 'notes' => null],
            ['code' => 'D33', 'category' => 'MAINTENANCE', 'sub_category' => 'Preventive', 'name' => 'Penggantian oli/fluida sesuai interval', 'weight' => 2.0, 'is_mandatory' => false, 'evidence_minimum' => 'Record', 'pic_verification' => 'Fleet', 'frequency' => 'Periodik', 'notes' => null],
            ['code' => 'D34', 'category' => 'MAINTENANCE', 'sub_category' => 'Corrective', 'name' => 'Temuan kerusakan memiliki corrective action dan status closure', 'weight' => 3.0, 'is_mandatory' => true, 'evidence_minimum' => 'WO/CA record', 'pic_verification' => 'Fleet / HSE', 'frequency' => 'Setiap temuan', 'notes' => null],
            ['code' => 'D35', 'category' => 'MAINTENANCE', 'sub_category' => 'Corrective', 'name' => 'Tidak ada outstanding defect kritis sebelum kendaraan beroperasi', 'weight' => 4.0, 'is_mandatory' => true, 'evidence_minimum' => 'Inspection/WO', 'pic_verification' => 'Fleet / HSE', 'frequency' => 'Setiap operasional', 'notes' => 'Kritis'],
            ['code' => 'D36', 'category' => 'MAINTENANCE', 'sub_category' => 'Record', 'name' => 'Riwayat maintenance terdokumentasi dan dapat ditelusuri', 'weight' => 2.0, 'is_mandatory' => false, 'evidence_minimum' => 'Maintenance history', 'pic_verification' => 'Fleet', 'frequency' => 'Bulanan', 'notes' => null],
            
            ['code' => 'D37', 'category' => 'MANAGEMENT', 'sub_category' => 'Monitoring', 'name' => 'Checklist inspeksi tersimpan dan dapat ditelusuri', 'weight' => 2.0, 'is_mandatory' => false, 'evidence_minimum' => 'Database/form', 'pic_verification' => 'HSE', 'frequency' => 'Bulanan', 'notes' => null],
            ['code' => 'D38', 'category' => 'MANAGEMENT', 'sub_category' => 'Improvement', 'name' => 'Temuan berulang dianalisis untuk tindakan pencegahan', 'weight' => 2.0, 'is_mandatory' => false, 'evidence_minimum' => 'Trend/analysis', 'pic_verification' => 'HSE / Fleet', 'frequency' => 'Bulanan', 'notes' => null],
            ['code' => 'D39', 'category' => 'MANAGEMENT', 'sub_category' => 'Reporting', 'name' => 'Laporan performa Driver & Kendaraan dibuat secara berkala', 'weight' => 2.0, 'is_mandatory' => false, 'evidence_minimum' => 'Report/dashboard', 'pic_verification' => 'HSE', 'frequency' => 'Bulanan', 'notes' => null],
            ['code' => 'D40', 'category' => 'MANAGEMENT', 'sub_category' => 'Improvement', 'name' => 'Ada improvement/inovasi yang terbukti meningkatkan safety/compliance', 'weight' => 3.0, 'is_mandatory' => false, 'evidence_minimum' => 'Before-after/evidence', 'pic_verification' => 'HSE', 'frequency' => 'Per periode', 'notes' => 'Poin inovasi'],
        ];

        foreach ($criteria as $criterion) {
            AssessmentCriterion::updateOrCreate(
                ['code' => $criterion['code']],
                $criterion
            );
        }
    }
}
